name: Metrics

on:
  schedule:
    - cron: "0 0 * * *" # daily at 00:00 UTC
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: stefanlight8
          template: classic
          base: header, activity, community, repositories, metadata
          config_octicon: yes
          # User Habits
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          # Languages
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 4
          plugin_languages_other: yes
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 150
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          # Repositories
          plugin_repositories: yes
          plugin_repositories_featured: discord-ram/discord-ram, gemini-async, minenv, filan
          plugin_repositories_order: featured, pinned, starred, random
          # Wakatime
          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_sections: time, editors, os
          plugin_wakatime_user: current
          plugin_wakatime_token: ${{ secrets.WAKATIME_KEY }}
